<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>

<br/>
<!-- footer -->
<div class="jumbotron text-center" style="margin-bottom: 0">
	<p>Generated by dev.Chunsikeu</p>
	<p>🇰🇷 Changwon, Republic of South Korea</p>
	<p>📱 010 . 1111. 1111</p>
</div>

</body>
</html>