<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>

<br/>
<!-- footer -->
<div class="jumbotron text-center" style="margin-bottom: 0">
	<p>Generated by dev.Chunsikeu</p>
	<p>🇰🇷 Changwon, Republic of South Korea</p>
	<p>📱 010 . 1111. 1111</p>
</div>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>